"""changing restaurant column name

Revision ID: 898e4f5c8d7d
Revises: d25af3559cf6
Create Date: 2023-09-04 08:00:00.211177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898e4f5c8d7d'
down_revision: Union[str, None] = 'd25af3559cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('names', sa.String(), nullable=True))
    op.drop_column('restaurants', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurants', 'names')
    # ### end Alembic commands ###
